backend:
  name: git-gateway
  repo: Mucunguzi256/ hfhcd
  branch: main
  auth_ type: pkce
  base_ url: https://auth. decapbridge. com
  auth_ endpoint: / sites/ dc335db9-2a5e-47b2- ba05-bdea4e2e3/ pkce
  auth_ token_ endpoint: / sites/ dc335db9-2a5e-47b2- ba05-bdea4e2e3/ token
  gateway_ url: https://gateway. decapbridge. com

commit_ messages:
  create: Create {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
  update: Update {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
  delete: Delete {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
  uploadMedia: Upload "{{path}}" - {{author-name}} <{{author-login}}> via DecapBridge
  deleteMedia: Delete "{{path}}" - {{author-name}} <{{author-login}}> via DecapBridge
  openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

auth:
  email_ claim: email
  first_ name_ claim: first_ name
  last_ name_ claim: last_ name
  avatar_ url_ claim: avatar_ url

logo_ url: https:// decapbridge. com/ decapcms-with- bridge. svg

site_ url: https://www. hfhcd. org

media_ folder: "public/images/uploads"

collections:
  - name: "causes"
    label: "Causes"
    folder: "src/content/ causes"
    create: true
    slug: "{{fields. title}}"
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Description", name: "description", widget: "text"}
      - { label: "Goal", name: "goal", widget: "number", required: false}
      - { label: "Raised", name: "raised", widget: "number", required: false}
      - { label: "Image", name: "image", widget: "image", required: false}
      - { label: "Content", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    folder: "src/content/ pages"
    create: true
    slug: "{{fields. title}}"
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Content", name: "body", widget: "markdown"}